branches:
  only:
  - master

dist: trusty

language: node_js

node_js:
- 8
- 10

install:
- npm install --prefix client/
- npm install --prefix server/
- npm install --prefix test/

script:
- npm run lint --prefix client/
- npm run lint --prefix server/
- npm run lint --prefix test/
- npm test --prefix test/

notifications:
  email:
    recipients:
      - ibc@aliax.net
    on_success: change
    on_failure: always
